export const featured = [
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "New York City, NYC",
    totalUnits: 89,
    occupancy: "50%",
    size: 40223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Jersey City, NJ",
    totalUnits: 89,
    occupancy: "70%",
    size: 30223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Maryland, Baltimore",
    totalUnits: 89,
    occupancy: "90%",
    size: 70223,
  },
];

export const homePageActiveListings = [
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "New York City, NYC",
    totalUnits: 89,
    occupancy: "50%",
    size: 40223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Jersey City, NJ",
    totalUnits: 89,
    occupancy: "70%",
    size: 30223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Maryland, Baltimore",
    totalUnits: 89,
    occupancy: "90%",
    size: 70223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "New York City, NYC",
    totalUnits: 89,
    occupancy: "50%",
    size: 40223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Jersey City, NJ",
    totalUnits: 89,
    occupancy: "70%",
    size: 30223,
  },
  {
    id: Math.random() * 100,
    img: "images/sampleImg.png",
    location: "Maryland, Baltimore",
    totalUnits: 89,
    occupancy: "90%",
    size: 70223,
  },
];

export const courseDetails = [
  {
    id: Math.random() * 100,
    tutorImg: "images/tutor.png",
    img: "images/learnImg.png",
    name: "Raza",
    action: "Buy",
    time: "3 days ago",
    title: "Learn everything about managing and operating a self storage!",
  },
  {
    id: Math.random() * 100,
    tutorImg: "images/tutor.png",
    img: "images/learnImg.png",
    name: "Raza",
    action: "Operate",
    time: "1 day ago",
    title: "Learn everything about managing and operating a self storage!",
  },
  {
    id: Math.random() * 100,
    tutorImg: "images/tutor.png",
    img: "images/learnImg.png",
    name: "Raza",
    action: "Buy",
    time: "7 days ago",
    title: "Learn everything about managing and operating a self storage!",
  },
  {
    id: Math.random() * 100,
    tutorImg: "images/tutor.png",
    img: "images/learnImg.png",
    name: "Raza",
    action: "Buy",
    time: "7 days ago",
    title: "Learn everything about managing and operating a self storage!",
  },
];
